name: Deploy HTML via GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # 👇 This step preloads the required action to avoid the error
      - name: Preload upload-artifact@v3
        uses: actions/upload-artifact@v3
        with:
          name: preload
          path: index.html

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
