name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site to artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Adjust path if your HTML is in a subdirectory

      # Add this step to pre-fetch the required action
      - name: Pre-fetch upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md  # Any small file just to make this step valid

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
